name: smooth_list_view
description: ListView constructors that implement smooth scrolling when using a mouse and scrolling with arrow keys.
version: 2.0.2
repository: https://github.com/dridino/smooth_list_view
issue_tracker: https://github.com/dridino/smooth_list_view/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - animation
  - ui
  - widgets
  - web

screenshots:
  - description: 'This screenshot shows the scrolling behavior of a standard ListView'
    path: assets/without.gif
  - description: 'This screenshot shows the scrolling behavior of a ListView provided by this package'
    path: assets/with.gif
    